version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: crudgames
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10

  backend:
    build: ./server
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=myappuser
      - DB_PASSWORD=myapppassword
      - DB_NAME=crudgames
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data: